name: offer
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_animated: ^3.2.0
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.4.0
  dropdown_search: ^5.0.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_offline: ^3.0.1
  flutter_polyline_points: ^2.0.0
  flutter_svg: ^2.0.9
  fluttericon: ^2.0.0
  font_awesome_flutter: ^10.6.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^13.0.1
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  grouped_list: ^5.1.2
  image_picker: ^1.0.7
  image_pickers: ^2.0.4+8
  intl: ^0.18.1
  jiffy: ^6.2.1
  path: ^1.8.3
  qr_flutter: ^4.1.0
  responsive_builder: ^0.7.0
  scan: ^1.6.0
  shared_preferences: ^2.2.2
  show_up_animation: ^2.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.1
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: reboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

          
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic.ttf
         
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
